### PR TITLE
Post deploy tests

### PR DESCRIPTION
**Pull request by trieloff**
@tripodsan fyi: this could be useful for our project template: it adds another testing step that will happen after the action has been deployed, but before it is being linked, making sure that only good actions will linked, i.e. actions that pass an in-runtime integration test.

### CODE REVIEW

**Comment by tripodsan** [comment]
cool, but this is already performed during `wsk-builder -v --deploy --test`

**Comment by tripodsan** [comment]
I guess, we just need to fix https://github.com/adobe/openwhisk-action-builder/issues/34

**Comment by trieloff** [comment]
I'd like to be able to write more complex assertions than just the `status===200` example I have now.

**Comment by tripodsan** [comment]
> I'd like to be able to write more complex assertions than just the `status===200` example I have now.

ideally, the same assertions we'd use to validate the action via pingdom.

**Comment by trieloff** [comment]
Not sure about that, because I wouldn't want to perform writes on ever ping. Doing a write for each deployment is less troublesome.

**Pull request merged**
